# Generated by Django 2.0 on 2018-03-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationdetails',
            name='invite_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitationdetails',
            name='food_preference_other',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invitationdetails',
            name='song_choice',
            field=models.TextField(blank=True, default=''),
        ),
    ]
